# Generated by Django 3.2.1 on 2021-07-22 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='作者名')),
                ('introduction', models.TextField(default='暂无简介', verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='网站名')),
                ('domain', models.CharField(max_length=70, unique=True, verbose_name='域名')),
                ('rule', models.JSONField(verbose_name='匹配规则')),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='小说名')),
                ('uid', models.CharField(help_text='md5(novelName_id;novelAuthor_id)', max_length=100, unique=True, verbose_name='UID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.author', verbose_name='作者')),
            ],
        ),
    ]
